In [2]:
import pandas as pd

### Loading Census Data

In [9]:
census_df = pd.read_csv('./Data/census-data.csv')
census_df.columns = census_df.iloc[0]
census_df = census_df.drop(census_df.index[0])
census_df.head(10)

,Geography,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000","Margin of Error!!Households!!Total!!Less than $10,000","Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households!!Total!!$10,000 to $14,999","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households!!Total!!$15,000 to $24,999",...,Margin of Error!!Nonfamily households!!Median income (dollars),Estimate!!Nonfamily households!!Mean income (dollars),Margin of Error!!Nonfamily households!!Mean income (dollars),Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,NaN
1,1600000US0103076,"Auburn city, Alabama",29136,1766,16.8,5.2,7.7,3.1,6.8,3.6,...,5866,29073,6941,(X),(X),(X),(X),37.3,(X),NaN
2,1600000US0107000,"Birmingham city, Alabama",87570,3579,12.8,1.9,7.7,1.7,14.3,2.2,...,3913,43672,3811,(X),(X),(X),(X),36.4,(X),NaN
3,1600000US0121184,"Dothan city, Alabama",30301,1019,9.8,1.8,6.5,1.3,10.4,2.0,...,1939,39334,4437,(X),(X),(X),(X),35.9,(X),NaN
4,1600000US0135896,"Hoover city, Alabama",36721,2222,4.7,2.1,2.3,1.3,5.7,2.6,...,11502,57314,10750,(X),(X),(X),(X),38.5,(X),NaN
5,1600000US0137000,"Huntsville city, Alabama",96551,2703,6.2,1.7,3.9,1.1,5.6,1.5,...,5816,61473,6112,(X),(X),(X),(X),29.5,(X),NaN
6,1600000US0150000,"Mobile city, Alabama",77991,3003,10.3,1.9,6.4,1.5,11.6,1.8,...,3334,38999,3296,(X),(X),(X),(X),46.5,(X),NaN
7,1600000US0151000,"Montgomery city, Alabama",81529,2059,9.3,2.2,7.9,2.2,11.4,2.3,...,4193,44762,4337,(X),(X),(X),(X),37.0,(X),NaN
8,1600000US0177256,"Tuscaloosa city, Alabama",39266,2801,13.4,4.2,6.8,2.9,10.7,3.1,...,3711,48747,10279,(X),(X),(X),(X),43.2,(X),NaN
9,1600000US0203000,"Anchorage municipality, Alaska",109584,2068,4.8,1.6,2.3,0.9,5.4,1.1,...,5147,70338,6361,(X),(X),(X),(X),27.7,(X),NaN
10,1600000US0404720,"Avondale city, Arizona",26611,1944,7.1,3.2,3.8,2.3,3.4,2.1,...,8083,49342,8205,(X),(X),(X),(X),46.0,(X),NaN